### ISSUE TITLE
How do you build this?

### ISSUE THREAD

**Issue by jsoldi** [bennn/pierce-categories#1]
Sorry this is probably not an actual issue but I'd really like to get the PDF version of this. I downloaded MiKTeX and tried to build this but keep getting errors. I thought it may be because of missing packages but can't find most of the packages listed on the file using the package manager. Mind sharing a PDF version of this or providing some instructions on how to build it?

**Comment by bennn** [comment]
Hi,

1. I pushed some instructions for building [here](https://github.com/bennn/pierce-categories/commit/b6c337d969208095c92fa9bc1f394eb927617ac1) --- if these don't help, let me know and I'll try again.

2. Attached is a zipfile with pdf versions of all the `.tex` files
[all.zip](https://github.com/bennn/pierce-categories/files/2180989/all.zip)

**Comment by jsoldi** [comment]
Thanks! I'll give the build instructions a try and let you know if I find any issue.

Also, since you asked to be let known if we found any errors, although I'm not sure if there is an actual error on 1.3.2, I found these alternative proofs which seem more straightforward and only use category theory concepts. I think they could also be applied to 1.3.3 but with the arrows reversed (although I think that's exactly what you do on the first part of 1.3.3). 

Let $f : B \rightarrow C$ and $g : C \rightarrow D$ be monic arrows. Also, let $a : A \rightarrow B$ and $b : A \rightarrow B$. We want to show that $(g \circ f) \circ a = (g \circ f) \circ b$ implies $a = b$. By associativity, the assumption is equivalent to $g \circ (f \circ a) = g \circ (f \circ b)$. Since $g$ is monic, then $f \circ a = f \circ b$, but since $f$ is also monic, then $a = b$. 

For the second part, let $f : B \rightarrow C$ and $g : C \rightarrow D$ such that $g \circ f$ is monic. Also, let $a : A \rightarrow B$ and $b : A \rightarrow B$. We want to show that $f \circ a = f \circ b$ implies $a = b$. If we assume $f \circ a = f \circ b$, then they are interchangable, so $g \circ (f \circ a) = g \circ (f \circ b)$, which can be rewritten as $(g \circ f) \circ a = (g \circ f) \circ b$. But since $(g \circ f)$ is monic, then $a = b$.

**Comment by bennn** [comment]
yes, this is better --- I'll push an update (edit: https://github.com/bennn/pierce-categories/commit/20806f3b43b74f744dc8e3192bc9e03b0c38907f)
